# Standards: 0.1
---
- name: Fact spectacle user
  set_fact:
    spectacle_user: "{{ spectacle_user | default(homebrew_user) | default(ansible_user_id) }}"
  tags:
    - spectacle

- become: "{{ (spectacle_user != ansible_user_id) | bool }}"
  become_user: "{{ spectacle_user }}"
  block:
    - name: Install required package
      ignore_errors: True
      homebrew_cask:
        name: spectacle
        greedy: True
        options: appdir=/Applications
        accept_external_apps: False
        state: upgraded
      tags:
        - spectacle

- name: Remove quarantine flag
  register: spectacle_quarantine
  failed_when: spectacle_quarantine.rc != 0 and "No such xattr" not in spectacle_quarantine.stderr
  changed_when: spectacle_quarantine.rc == 0
  command: xattr -d com.apple.quarantine /Applications/Spectacle.app
  tags:
    - spectacle

...
