# Standards: 0.1
---
- name: Kill spectacle
  command: killall Spectacle
  register: spectacle_kill
  failed_when: spectacle_kill.rc != 0 and "No matching processes belonging to you were found" not in spectacle_kill.stderr
  become: "{{ (spectacle_user != ansible_user_id) | bool }}"
  become_user: "{{ spectacle_user }}"

- name: Start spectacle
  when: spectacle_started
  command: open -j /Applications/Spactacle.app
  become: "{{ (spectacle_user != ansible_user_id) | bool }}"
  become_user: "{{ spectacle_user }}"

...
